# Generated by Django 3.2.8 on 2023-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
